name: Publish new website version

on:
  push:
    branches:
      - master

jobs:
  publish-gatsby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.MODINO_CI_GITHUB_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
